CREATE TABLE COURSE (
  COURSE_ID   NUMBER(4) PRIMARY KEY,
  COURSE_NAME VARCHAR2(30) NOT NULL,
  FEES        NUMBER(8,2)
);

CREATE TABLE STUDENT (
  STUDENT_ID NUMBER(4) PRIMARY KEY,
  SNAME      VARCHAR2(30) NOT NULL,
  EMAIL      VARCHAR2(40),
  PHONE      VARCHAR2(15),
  CITY       VARCHAR2(20)
);

CREATE TABLE ENROLLMENT (
  ENROLL_ID  NUMBER(5) PRIMARY KEY,
  STUDENT_ID NUMBER(4),
  COURSE_ID  NUMBER(4),
  ENROLL_DATE DATE,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (COURSE_ID)  REFERENCES COURSE(COURSE_ID)
);
Commit;

INSERT INTO COURSE VALUES (101, 'JAVA', 5000);
INSERT INTO COURSE VALUES (102, 'PYTHON', 4500);
INSERT INTO COURSE VALUES (103, 'SQL', 4000);

INSERT INTO STUDENT VALUES (1, 'ARUN', 'arun@mail.com', '9876543210', 'CHENNAI');
INSERT INTO STUDENT VALUES (2, 'BALA', 'bala@mail.com', '9876501234', 'DELHI');
INSERT INTO STUDENT VALUES (3, 'CATHY', 'cathy@mail.com', '9123456780', 'MUMBAI');

INSERT INTO ENROLLMENT VALUES (1001, 1, 101, SYSDATE);
INSERT INTO ENROLLMENT VALUES (1002, 2, 102, SYSDATE);
INSERT INTO ENROLLMENT VALUES (1003, 3, 103, SYSDATE);
INSERT INTO ENROLLMENT VALUES (1004, 1, 103, SYSDATE);

--Basic Selection--
SELECT * from Student;
SELECT SNAME, CITY from Student;
SELECT COURSE_NAME, FEES from Course;
SELECT * FROM STUDENT WHERE CITY='CHENNAI';
SELECT * FROM COURSE ORDER BY FEES DESC;

--WHERE, LIKE, IN BETWEEN--
SELECT * FROM STUDENT WHERE SNAME LIKE 'A%';
SELECT * FROM STUDENT WHERE CITY='CHENNAI' OR CITY='DELHI';
SELECT * FROM COURSE WHERE FEES BETWEEN 4000 AND 5000;
SELECT * FROM STUDENT WHERE PHONE LIKE '%10';
SELECT * FROM STUDENT WHERE EMAIL LIKE '%mail%';

--Aggregate & GROUP BY--
SELECT COUNT(STUDENT_ID) AS TOTAL_STUDENT FROM STUDENT;
SELECT * FROM COURSE WHERE FEES=(SELECT MAX(FEES) FROM COURSE);
SELECT * FROM COURSE WHERE FEES=(SELECT MIN(FEES) FROM COURSE);
SELECT CITY,COUNT(CITY) FROM STUDENT GROUP BY CITY;
SELECT  AVG(FEES)AS AVERAGE_FEES FROM COURSE;

--JOINS--
SELECT s.SNAME, c.COURSE_NAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID;
SELECT s.SNAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID WHERE c.COURSE_NAME='JAVA';
SELECT c.COURSE_NAME, COUNT(s.STUDENT_ID) FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID GROUP BY c.COURSE_NAME;
SELECT S.SNAME, c.COURSE_NAME, e.enroll_date FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID;

--SUBQUERY--
SELECT s.SNAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID WHERE c.FEES=(SELECT MAX(FEES) FROM COURSE);
SELECT s.SNAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID GROUP BY s.STUDENT_ID, s.SNAME HAVING COUNT(e.COURSE_ID) > 1;
SELECT c.COURSE_NAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID WHERE s.SNAME='ARUN';
SELECT s.SNAME FROM STUDENT s JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID WHERE s.STUDENT_ID NOT IN(SELECT STUDENT_ID FROM ENROLLMENT);

--UPDATE AND ALTER--
UPDATE COURSE SET FEES=FEES+(0.1*FEES);
UPDATE STUDENT SET CITY='PUNE' WHERE SNAME='BALA';
DELETE FROM ENROLLMENT WHERE STUDENT_ID IN (SELECT STUDENT_ID FROM STUDENT WHERE CITY = 'MUMBAI');
DELETE FROM STUDENT WHERE CITY = 'MUMBAI';

--CONSTRAINT PARCTICE--
ALTER TABLE STUDENT ADD CONSTRAINT UQ_STUDENT_EMAIL UNIQUE (EMAIL);
ALTER TABLE COURSE MODIFY COURSE_NAME VARCHAR2(30) NOT NULL;
INSERT INTO STUDENT VALUES (4, 'VARUN', 'arun@mail.com', '9111222333', 'DELHI');
